[versions]
kotlin = "1.9.22"
compose = "1.6.0"

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }

[libraries]

androidx-annotations = { group = "androidx.annotation", name = "annotation", version = "1.7.1" }

